### ISSUE TITLE
No parity data for weekends

### ISSUE THREAD

**Issue by yemreinci** [bounswe/bounswe2019group2#120]
## Prerequisite

- [x] I am using the latest version of the code, and checked the documentation related to my needs.

* **I'm submitting a ... (remove the irrelevant one)**
  - [x] bug report

There is no parity data in this dates also other weekends :). (Other than EUR/EUR parity in 2019-05-05 which I added manually.) Checkout:
https://api.traiders-practice.tk/parity/2019-05-05/
https://api.traiders-practice.tk/parity/2019-05-04/

I think the source of the problem is the API that we are using. Checkout: https://api.exchangeratesapi.io/history?start_at=2019-05-01&end_at=2019-05-06&base=EUR
The /history endpoint does not return anything for weekends. 

However, http://api.exchangeratesapi.io/2019-05-05, this endpoint returns the same data on last Friday.

@mertyg, I think we should change the **generatehistory** command according to this problem.

* **Deadline for resolution:** 12.05.2019

**Comment by fatih-iver** [comment]
For the EUR/EUR case, the website says invalid request but we handle this case in code by checking whether the base symbol and the target symbol are equal or not. We don't need to keep records for these cases since they always equal to 1 anytime. It will be just redundant data. 

For the other case, we may consider changing the API however since this is a demo I think it is not really important for now. In addition to that, this API only provides information related to currencies. In Traider, we will need much more than that. e.g. commodities.
