### ISSUE TITLE
Sequence Diagram

### ISSUE THREAD

**Issue by mcanbayraktar** [bounswe/bounswe2019group2#36]
Deadline =  March 17th, 10:00

**Comment by mertyg** [comment]
Key use cases that will be presented in the diagrams:
Please update this list if you are planning to do a diagram for any of the below use cases, to prevent conflicts.

- [x] Sign Up - Mert
- [x] Sign In - Dilruba
- [x] Post Comment to Article - Mert
- [x] Make Investment - Mert
- [x] Search Equipment - Dilruba
- [ ] Create Portfolio 
- [ ] Post Article
- [ ] Track Event
- [ ] Predict Equipment
- [ ] Buy/Sell Order
- [ ] Follow a user

**Comment by mertyg** [comment]
The below list and checkmarks indicate the updated sequence diagrams. Could you please mark them as you update them, so that when we are done we can have somebody review them?

- [x] Sign In - Mert
- [ ] Sign Up - Dilruba
- [x] Post Comment to Article - Mert
- [x] Make Investment - Mert
- [ ] Search Equipment - Dilruba
- [ ] Create Portfolio -Adil
- [ ] Post Article-Adil
- [ ] Track Event-Yunus K.
- [ ] Predict Equipment-Yunus K.
- [ ] Buy Order-Özgür
- [ ] Follow a user- Özgür

**Comment by mertyg** [comment]
@yemreinci can you please review the sequence diagrams?

**Comment by mertyg** [comment]
all of the sequence diagrams are completed and we reviewed and updated them w/ @yemreinci once again. closing the issue.
